### PR TITLE
fix(workflows): recover terminal artifact commits

### LINKED ISSUE #110: workflows: terminal artifact set (result.json + workflow.json) is not committed atomically
## Description

Verified by read-only audit (`seal/gpt-5.6-sol` subagent, verdict: CONFIRMED).

`persistWorkflowJson` writes artifacts as a multi-step sequence of individually-atomic writes:

- `extensions/workflows/artifacts.ts:154-165` — `transcripts.json` and optionally `journal.json`
- `artifacts.ts:167-172` — atomic replace of `result.json`
- `artifacts.ts:174-185` — compact manifest with `resultArtifact: "result.json"` written **separately** to `workflow.json`

`writeFileAtomic` (`serialization.ts:147-161`) is a temp-write + `renameSync` per file — no directory-level transaction.

## Impact

Crash window: after the `result.json` rename succeeds and before the `workflow.json` rename succeeds, readers retain the prior manifest (typically `running`, without `resultArtifact`). Consequences:

- `hydrateRunArtifacts` (`dashboard.ts:102-114`) reads `result.json` only when the manifest references it.
- Restart recovery (`index.ts:972-990`) and status recovery (`index.ts:2212-2226`) are manifest-driven and never probe an unreferenced `result.json`.
- Stale-run recovery (`dashboard.ts:483-514`) flips persisted `running` to `uncertain` without inspecting `result.json`.
- **No GC, cleanup, or orphan-detection path exists** — the terminal result stays orphaned indefinitely and the run is reported as `running`/`uncertain` instead of terminal.

## Test coverage gap

`execute.e2e.test.ts:297-302` covers successful persistence and individual atomic replacement, but not failure/crash between the `result.json` and `workflow.json` writes.

## Suggested fix

Commit a single manifest only after all dependent artifacts are durably prepared (e.g. transaction-like temp run directory + rename, or a manifest generation/commit marker). Additionally, recovery should detect and reconcile orphan `result.json` artifacts instead of trusting only the old manifest.

Related: #107, #108, #109 (same delivery/persistence subsystem).

Found by automated workflow audit (run `wf_56028a5b018b`).

### PR DESCRIPTION
**Pull request by testikun**
## Problem

A Workflow process crash after writing terminal side artifacts but before the final manifest can orphan valid result/transcript evidence. The initial recovery design also allowed an older completed receipt to overwrite newer failed or cleanup facts. Closes #110.

## Value

Verified terminal artifacts become discoverable after a crash without treating arbitrary files as success, and recovery cannot roll back a newer canonical manifest.

## Approach

Publish the terminal reference-free manifest, then a bounded receipt containing its exact SHA-256 predecessor identity, the intended final manifest, and fixed side-artifact names/sizes/digests. Promote only when artifacts validate and the canonical predecessor still matches. Already-committed manifests retain later delivery/resource updates. Missing, modified, malformed or superseding canonical state fails closed. Run recovery at the shared persisted-read boundary and before delivery updates.

## Validation

Integrated current main and repaired the reproduced failed-to-completed rollback. Focused regressions passed 49/49. `bun run check` and standard `bun run test` passed: 1466 Node tests, one platform skip, Vitest 30/30. Two independent final reviews are clean on `3710707286930481c0b95af316abd911d8e6afef`, integrated with main `b0fc5588cd6ae514cc4a64db87ab1c899d2f034f` including #423. Final-head remote CI passed on Node 22.19.0, Node 24 and Windows: https://github.com/openpi-dev/openpi/actions/runs/34078645725. The historical requested change about already-committed identity is addressed, as acknowledged by its reviewer; the final implementation also guards the uncommitted predecessor against newer canonical updates.

## Impact

No model tool, permission or configuration change. Persisted terminal writes briefly include a bounded `.workflow-commit.json` receipt. Legacy runs without receipts remain readable; the unshipped receipt shape now requires predecessorSha256. If an uncommitted manifest changes before recovery, recovery conservatively retains that newer canonical state and the receipt for inspection rather than silently replacing it. The protocol covers process-crash recovery across existing atomic file replacements, not power-loss durability/fsync or a filesystem-wide transaction.

[Architecture and evidence](https://github.com/testikun/openpi/blob/codex/issue-110-artifact-commit/docs/architecture/WORKFLOW_ARTIFACT_COMMIT.md).

### CODE REVIEW

**Comment by testikun** [comment]
CI status note: Node 22/24 completed this PR's repository checks and failed only at the final fresh-install `Smoke-test packed standalone Web CLI` step, where the child exits before the test can read its URL. The same failure now occurs on unrelated PRs #385, #386, and #387.

I reproduced the packed install independently: npm now admits Pi 0.85.0 through OpenPI's published `peerDependencies: "*"`; the CLI then exits with `Cannot find module '@earendil-works/pi-server'`. The checkout/lock-based `bun run check` and full test suite remain green. I recorded the shared packaging regression and suggested peer-range follow-up in #328: https://github.com/openpi-dev/openpi/issues/328#issuecomment-5539313015

No dependency workaround is mixed into this feature PR.

**Review by tt-a1i — CHANGES_REQUESTED** [review]
## 需要改：「已提交」不要用整份 `workflow.json` 字节当身份

文档写 crash 在 unlink 之后是 harmless，因为 recovery 认得 already-committed manifest。实现用 **整份 `workflow.json` 字节相等** 判断 already-committed。

这不是无害窗口：`persistWorkflowDeliveryState`、#382 的 delivery owner、#379 的 `resourceRefs` 都会改同一份文件。下一轮 `recoverPendingWorkflowCommit` 会把收据里**更旧的** manifest 写回去。

请用 run id + 终态 + artifact 引用（名字/digest）判断 already-committed，不要比整文件字节。和 #379/#382 叠在 `artifacts.ts` 上之前，先把这个身份修好。

**Comment by testikun** [comment]
已按 review 修复并推送到 `fd2842f`：恢复时不再用整份 `workflow.json` 字节相等判断 already-committed，而是校验 run id、终态和 artifact 引用；因此 delivery owner/receipt 等后续字段更新不会被旧 marker manifest 覆盖。新增回归测试验证已有新 delivery 字段会被保留。artifacts 测试 18/18 通过，Biome 和 diff 检查通过。

File: docs/architecture/WORKFLOW_ARTIFACT_COMMIT.md [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+Persisted Workflow reads and delivery-receipt updates check for a pending commit before consuming `workflow.json`. Recovery promotes the recorded manifest only when all of these facts hold:
+
+- the receipt is a regular, non-symlink file within its byte budget;
+- the receipt version and run id match the containing generated run directory;
+- the recorded manifest is bounded JSON for a known terminal state;
+- artifact names are unique members of the fixed `result.json`, `transcripts.json`, and `journal.json` set;
+- manifest references agree exactly with the receipt's artifact set;
+- every artifact is a regular, non-symlink file whose byte count and SHA-256 digest match the receipt.
+
+If the final manifest is already byte-identical, recovery only removes the stale receipt. If every artifact validates and the manifest is still the earlier terminal projection, recovery atomically completes the manifest commit. Missing, truncated, substituted, oversized, malformed, or path-traversing evidence never gains an artifact reference.
```
Comment (tt-a1i) [inline docs/architecture/WORKFLOW_ARTIFACT_COMMIT.md]: [P2] Update the already-committed contract after the identity fix

The current `hasCommittedManifest` intentionally accepts a manifest with matching runId/status/artifact references even when delivery or resourceRefs make its bytes differ. This sentence still promises byte equality, which describes the old bug. State the terminal commit identity plus artifact-digest check, and refresh the document source boundary to the reviewed implementation.

**Review by tt-a1i — COMMENTED** [review]
Exact-head follow-up on fd2842f8a5ee1e67d37db2ba10f48a957e884b9b: the prior already-committed identity blocker is addressed. The implementation compares runId/status/artifact references after checking artifact size/digests, rather than requiring whole-file manifest equality.

Verification in an isolated exact-head worktree: artifacts tests 18/18, dashboard tests 25/25, plus a direct probe confirming that delivery/resourceRefs survive a leftover receipt, a pre-manifest crash is recovered, and an incomplete receipt does not publish references. All commands exited 0. No new P0/P1 was confirmed in this bounded review.

Please update the architecture text below to match the corrected identity rule. This PR changes recovery writes reached through persisted workflow reads, so this comment is not final integration/runtime acceptance: current-main integration and its full required checks remain outstanding. No branch update or merge was performed in this review.

**Comment by testikun** [comment]
已按新增 P2 review 修正文档并推送 `f787df3`：architecture record 不再描述整份 workflow.json byte equality，而是明确使用 run id + terminal state + artifact references，并更新 source revision。实现与测试已在前一提交 `fd2842f` 验证。

**Comment by testikun** [comment]
已修正文档语义：already-committed 由 run id、终态和 artifact 引用身份判断，不再使用整份 workflow.json 字节相等；CI 与 focused tests 均通过。

**Comment by testikun** [comment]
已按当前 review 状态完成本轮协作：相关修复/主线同步已推送到最新 head；inline review threads 已 resolved。GitHub required CI 正在重跑/排队，请基于最新 head 复审。

**Comment by testikun** [comment]
@tt-a1i 最新 head 的 review 修复、main 冲突同步和 required CI 已完成；当前 Node 22/24 与 Windows checks 全绿，inline threads 也已 resolved。请基于最新提交重新复审。

File: docs/architecture/WORKFLOW_ARTIFACT_COMMIT.md (hunk 1 above)
Comment (testikun) [reply docs/architecture/WORKFLOW_ARTIFACT_COMMIT.md]: @tt-a1i 已同步 architecture record/source boundary：already-committed 身份使用 runId、terminal state 与 artifact refs/digest，不再比较整个 workflow.json。CI 已通过。

**Comment by testikun** [comment]
@tt-a1i 已修复：already-committed 改为校验 runId、terminal state、artifact refs/digest，不再使用整份 workflow.json 字节相等。

**Comment by testikun** [comment]
@tt-a1i 已同步 architecture record 与 source boundary，说明已改为 runId + terminal state + artifact refs/digest；当前 head CI 已通过。
